apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      component: httpd
  template:
    metadata:
      labels:
        component: httpd
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: httpd
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "15m"
          limits:
            memory: "32Mi"
            cpu: "30m"
