apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: hello-world-
namespace: hello-world

commonLabels:
  app: hello-world

resources:
- httpd-deployment.yaml
- httpd-svc.yaml
